export const TOURNAMENTS_ERROR = 'TOURNAMENTS_ERROR';
export const REQUEST_TOURNAMENTS = 'REQUEST_TOURNAMENTS';
export const RECEIVE_TOURNAMENTS = 'RECEIVE_TOURNAMENTS';
export const POST_TOURNAMENTS = 'POST_TOURNAMENTS';
export const FETCH_TOURNAMENTS = 'FETCH_TOURNAMENTS';
